In [2]:
#Test
#Load the Packages Needed
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [2]:
#Load the Data
pwt = pd.read_csv('https://raw.githubusercontent.com/jivizcaino/PWT_10.0/main/pwt100.csv', encoding="latin-1")
pwt

,countrycode,country,currency_unit,year,rgdpe,rgdpo,pop,emp,avh,hc,...,csh_x,csh_m,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_n,pl_k
0,ABW,Aruba,Aruban Guilder,1950,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABW,Aruba,Aruban Guilder,1951,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABW,Aruba,Aruban Guilder,1952,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABW,Aruba,Aruban Guilder,1953,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ABW,Aruba,Aruban Guilder,1954,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12805,ZWE,Zimbabwe,US Dollar,2015,40141.61719,39798.64453,13.814629,6.393752,NaN,2.584653,...,0.140172,-0.287693,-0.051930,0.479228,0.651287,0.541446,0.616689,0.533235,0.422764,1.533909
12806,ZWE,Zimbabwe,US Dollar,2016,41875.20313,40963.19141,14.030331,6.504374,NaN,2.616257,...,0.131920,-0.251232,-0.016258,0.470640,0.651027,0.539631,0.619789,0.519718,0.416510,1.491724
12807,ZWE,Zimbabwe,US Dollar,2017,44672.17578,44316.74219,14.236595,6.611773,NaN,2.648248,...,0.126722,-0.202827,-0.039897,0.473560,0.639560,0.519956,0.619739,0.552042,0.415592,1.514525
12808,ZWE,Zimbabwe,US Dollar,2018,44325.10938,43420.89844,14.438802,6.714952,NaN,2.680630,...,0.144485,-0.263658,-0.020791,0.543757,0.655473,0.529867,0.641361,0.561526,0.425143,1.590120
12809,ZWE,Zimbabwe,US Dollar,2019,42296.06250,40826.57031,14.645468,6.831017,NaN,2.713408,...,0.213562,-0.270959,-0.089798,0.494755,0.652439,0.500927,0.487763,0.430082,0.420675,1.384068

In [3]:
#Prepare the Dataset and Clean the Data
#pwt_subset = pwt[['country','countrycode','year','cgdpo','pop','emp','avh','hc','cn','labsh','ctfp']]
pwt_subset = pwt[['country','countrycode','year','cgdpo','pop','emp','hc','cn','labsh','ctfp']]
pwt_subset = pwt_subset[pwt_subset['year'] > 2009]
pwt_subset = pwt_subset.set_index('countrycode')
pwt_subset = pwt_subset.dropna()
pwt_subset

,country,year,cgdpo,pop,emp,hc,cn,labsh,ctfp
countrycode,,,,,,,,,
AGO,Angola,2010,153241.28130,23.356246,11.977833,1.417133,9.068128e+05,0.300495,0.305130
AGO,Angola,2011,199033.23440,24.220661,12.688628,1.424196,1.046118e+06,0.287628,0.370382
AGO,Angola,2012,221671.93750,25.107931,13.121690,1.431295,1.107735e+06,0.282355,0.408607
AGO,Angola,2013,228184.59380,26.015781,13.565423,1.438429,1.103819e+06,0.280897,0.432413
AGO,Angola,2014,243641.51560,26.941779,14.039274,1.445598,1.219780e+06,0.288775,0.442301
...,...,...,...,...,...,...,...,...,...
ZWE,Zimbabwe,2015,39455.90234,13.814629,6.393752,2.584653,6.179063e+04,0.533381,0.386632
ZWE,Zimbabwe,2016,40864.16406,14.030331,6.504374,2.616257,6.484419e+04,0.533381,0.385642
ZWE,Zimbabwe,2017,44316.74219,14.236595,6.611773,2.648248,6.762756e+04,0.533381,0.402779
ZWE,Zimbabwe,2018,43567.51172,14.438802,6.714952,2.680630,6.882677e+04,0.533381,0.382059
ZWE,Zimbabwe,2019,41081.72266,14.645468,6.831017,2.713408,6.958824e+04,0.533381,0.351973

In [4]:
#Choose the Year to Perform the Analysis
print(pwt_subset.groupby("year").count())

      country  cgdpo  pop  emp   hc   cn  labsh  ctfp
year
2010      118    118  118  118  118  118    118   118
2011      118    118  118  118  118  118    118   118
2012      118    118  118  118  118  118    118   118
2013      118    118  118  118  118  118    118   118
2014      118    118  118  118  118  118    118   118
2015      118    118  118  118  118  118    118   118
2016      118    118  118  118  118  118    118   118
2017      118    118  118  118  118  118    118   118
2018      118    118  118  118  118  118    118   118
2019      118    118  118  118  118  118    118   118

We will choose 2019: the latest year with the largets number of ebservations for our variables of interest.
*To Do: Robustness using 2010,2015, and an average for 2010-2019

In [5]:
#Descriptive Statistics for the Variables in our Dataset
print(pwt_subset[pwt_subset['year'] == 2019].describe([0.05,0.10,0.25,0.50,0.75,0.90,0.95]).round(2))

         year        cgdpo      pop     emp      hc            cn   labsh  \
count   118.0       118.00   118.00  118.00  118.00  1.180000e+02  118.00
mean   2019.0   1000698.85    54.32   24.23    2.83  4.557984e+06    0.51
std       0.0   2836363.16   184.87   87.88    0.69  1.233559e+07    0.12
min    2019.0      3577.58     0.29    0.13    1.22  1.696016e+04    0.16
5%     2019.0     11883.35     0.89    0.38    1.60  3.357834e+04    0.29
10%    2019.0     22909.33     1.83    0.67    1.77  7.934253e+04    0.33
25%    2019.0     43331.93     4.75    2.26    2.37  1.970589e+05    0.44
50%    2019.0    193587.16    11.13    5.00    2.90  7.156158e+05    0.53
75%    2019.0    690796.17    37.18   15.90    3.34  2.909915e+06    0.58
90%    2019.0   2289714.22    83.46   34.35    3.63  1.136341e+07    0.64
95%    2019.0   3272437.16   154.14   71.87    3.73  1.894103e+07    0.66
max    2019.0  20566034.00  1433.78  798.81    4.35  1.015442e+08    0.81

         ctfp
count  118.00
mean     0.63
std      0.23
min      0.05
5%       0.26
10%      0.34
25%      0.45
50%      0.64
75%      0.81
90%      0.91
95%      0.99
max      1.25

In [6]:
pwt_subset = pwt_subset[pwt_subset['year'] == 2019]
pwt_subset

,country,year,cgdpo,pop,emp,hc,cn,labsh,ctfp
countrycode,,,,,,,,,
AGO,Angola,2019,2.232893e+05,31.825295,16.644962,1.481984,1.371321e+06,0.331142,0.380317
ARG,Argentina,2019,9.785588e+05,44.780677,20.643215,3.096804,3.374818e+06,0.543918,0.812184
ARM,Armenia,2019,4.379569e+04,2.957731,0.966091,3.135995,9.894587e+04,0.548672,0.820758
AUS,Australia,2019,1.355143e+06,25.203198,12.863174,3.549666,5.899094e+06,0.571645,0.837903
AUT,Austria,2019,4.783293e+05,8.955102,4.550281,3.381046,2.875460e+06,0.583860,0.803706
...,...,...,...,...,...,...,...,...,...
USA,United States,2019,2.056603e+07,329.064917,158.299591,3.749341,6.905909e+07,0.597091,1.000000
VEN,Venezuela (Bolivarian Republic of),2019,7.162512e+03,28.515829,11.694400,2.893462,2.179051e+05,0.428571,0.054367
ZAF,South Africa,2019,7.350671e+05,58.558270,18.642710,2.908202,2.897706e+06,0.570888,0.542998
ZMB,Zambia,2019,5.681111e+04,17.861030,5.225448,2.686845,3.037242e+05,0.390301,0.255552
ZWE,Zimbabwe,2019,4.108172e+04,14.645468,6.831017,2.713408,6.958824e+04,0.533381,0.351973

In [8]:
pwt_subset['GDP_pw']       = pwt_subset['cgdpo']/pwt_subset['emp']
pwt_subset['GDP_pc']       = pwt_subset['cgdpo']/pwt_subset['pop']
pwt_subset['k']            = pwt_subset['cn']/pwt_subset['emp']
pwt_subset['emp_pop']      = pwt_subset['emp']/pwt_subset['pop']

pwt_subset['log_y_pw']       = np.log(pwt_subset['GDP_pw'])
pwt_subset['log_y_pc']       = np.log(pwt_subset['GDP_pc'])
pwt_subset['log_k']          = np.log(pwt_subset['k'])
pwt_subset['log_emp_pop']    = np.log(pwt_subset['emp_pop'])

pwt_subset['y_pw_relUS']     = pwt_subset['GDP_pw']/pwt_subset.at['USA','GDP_pw']
pwt_subset['y_pc_relUS']     = pwt_subset['GDP_pc']/pwt_subset.at['USA','GDP_pc']
pwt_subset['k_relUS']        = pwt_subset['k']/pwt_subset.at['USA','k']
pwt_subset['h_relUS']        = pwt_subset['hc']/pwt_subset.at['USA','hc']
pwt_subset['emp_pop_relUS']  = pwt_subset['emp_pop']/pwt_subset.at['USA','emp_pop']
pwt_subset

,country,year,cgdpo,pop,emp,hc,cn,labsh,ctfp,GDP_pw,...,emp_pop,log_y_pw,log_y_pc,log_k,log_emp_pop,y_pw_relUS,y_pc_relUS,k_relUS,h_relUS,emp_pop_relUS
countrycode,,,,,,,,,,,,,,,,,,,,,
AGO,Angola,2019,2.232893e+05,31.825295,16.644962,1.481984,1.371321e+06,0.331142,0.380317,13414.828363,...,0.523010,9.504116,8.855962,11.319178,-0.648154,0.103256,0.112260,0.188849,0.395265,1.087207
ARG,Argentina,2019,9.785588e+05,44.780677,20.643215,3.096804,3.374818e+06,0.543918,0.812184,47403.410950,...,0.460985,10.766449,9.992059,12.004465,-0.774390,0.364871,0.349645,0.374742,0.825960,0.958271
ARM,Armenia,2019,4.379569e+04,2.957731,0.966091,3.135995,9.894587e+04,0.548672,0.820758,45332.881212,...,0.326632,10.721788,9.602868,11.536825,-1.118920,0.348933,0.236921,0.234768,0.836412,0.678987
AUS,Australia,2019,1.355143e+06,25.203198,12.863174,3.549666,5.899094e+06,0.571645,0.837903,105350.608151,...,0.510379,11.565049,10.892447,13.035941,-0.672602,0.810898,0.860321,1.051226,0.946744,1.060948
AUT,Austria,2019,4.783293e+05,8.955102,4.550281,3.381046,2.875460e+06,0.583860,0.803706,105120.835121,...,0.508122,11.562866,10.885831,13.356534,-0.677034,0.809130,0.854648,1.448532,0.901771,1.056257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA,United States,2019,2.056603e+07,329.064917,158.299591,3.749341,6.905909e+07,0.597091,1.000000,129918.427818,...,0.481059,11.774662,11.042896,12.985984,-0.731766,1.000000,1.000000,1.000000,1.000000,1.000000
VEN,Venezuela (Bolivarian Republic of),2019,7.162512e+03,28.515829,11.694400,2.893462,2.179051e+05,0.428571,0.054367,612.473647,...,0.410102,6.417506,5.526157,9.832705,-0.891349,0.004714,0.004019,0.042712,0.771725,0.852499
ZAF,South Africa,2019,7.350671e+05,58.558270,18.642710,2.908202,2.897706e+06,0.570888,0.542998,39429.196353,...,0.318362,10.582262,9.437695,11.953975,-1.144567,0.303492,0.200849,0.356290,0.775657,0.661794
ZMB,Zambia,2019,5.681111e+04,17.861030,5.225448,2.686845,3.037242e+05,0.390301,0.255552,10872.007380,...,0.292561,9.293947,8.064866,10.970335,-1.229081,0.083683,0.050893,0.133234,0.716618,0.608161
ZWE,Zimbabwe,2019,4.108172e+04,14.645468,6.831017,2.713408,6.958824e+04,0.533381,0.351973,6013.998416,...,0.466425,8.701845,7.939188,9.228877,-0.762657,0.046291,0.044882,0.023351,0.723702,0.969580

In [ ]:
#An alternative way to compute variables is
#pwt_subset.assign( k = (pwt_subset.cn/pwt_subset.emp) )

# Development Accounting

In [15]:
#pwt_subset['y_hk_pw']     = (pwt_subset['k']**(1-pwt_subset['labsh']))*(( pwt_subset['hc']**pwt_subset['labsh']))
pwt_subset['y_hk_pw']       = (pwt_subset['k']**(1/3))*(( pwt_subset['hc']**(2/3) ))
pwt_subset['y_hk_pw_relUS'] = pwt_subset['y_hk_pw']/pwt_subset.at['USA','y_hk_pw']
pwt_subset

pwt_subset.describe([0.05,0.10,0.25,0.50,0.75,0.90,0.95]).round(2)

,year,cgdpo,pop,emp,hc,cn,labsh,ctfp,GDP_pw,GDP_pc,...,log_y_pc,log_k,log_emp_pop,y_pw_relUS,y_pc_relUS,k_relUS,h_relUS,emp_pop_relUS,y_hk_pw,y_hk_pw_relUS
count,118.0,118.00,118.00,118.00,118.00,1.180000e+02,118.00,118.00,118.00,118.00,...,118.00,118.00,118.00,118.00,118.00,118.00,118.00,118.00,118.00,118.00
mean,2019.0,1000698.85,54.32,24.23,2.83,4.557984e+06,0.51,0.63,54131.95,25812.16,...,9.64,11.91,-0.85,0.42,0.41,0.58,0.75,0.91,118.12,0.65
std,0.0,2836363.16,184.87,87.88,0.69,1.233559e+07,0.12,0.23,41237.12,23410.68,...,1.18,1.23,0.22,0.32,0.37,0.50,0.18,0.19,53.47,0.29
min,2019.0,3577.58,0.29,0.13,1.22,1.696016e+04,0.16,0.05,612.47,251.18,...,5.53,8.23,-1.50,0.00,0.00,0.01,0.33,0.46,19.61,0.11
5%,2019.0,11883.35,0.89,0.38,1.60,3.357834e+04,0.29,0.26,5591.77,2089.28,...,7.64,9.57,-1.25,0.04,0.03,0.03,0.43,0.59,34.50,0.19
10%,2019.0,22909.33,1.83,0.67,1.77,7.934253e+04,0.33,0.34,8706.20,3068.03,...,8.03,9.96,-1.17,0.07,0.05,0.05,0.47,0.65,42.82,0.23
25%,2019.0,43331.93,4.75,2.26,2.37,1.970589e+05,0.44,0.45,19563.16,7893.00,...,8.97,11.31,-0.95,0.15,0.13,0.19,0.63,0.80,77.91,0.43
50%,2019.0,193587.16,11.13,5.00,2.90,7.156158e+05,0.53,0.64,44401.67,17644.11,...,9.78,12.02,-0.82,0.34,0.28,0.38,0.77,0.92,113.09,0.62
75%,2019.0,690796.17,37.18,15.90,3.34,2.909915e+06,0.58,0.81,79304.20,39586.98,...,10.59,12.98,-0.70,0.61,0.63,1.00,0.89,1.03,168.45,0.92
90%,2019.0,2289714.22,83.46,34.35,3.63,1.136341e+07,0.64,0.91,105544.74,53854.87,...,10.89,13.29,-0.63,0.81,0.86,1.35,0.97,1.11,187.45,1.02
95%,2019.0,3272437.16,154.14,71.87,3.73,1.894103e+07,0.66,0.99,127517.65,72647.37,...,11.19,13.36,-0.57,0.98,1.16,1.45,0.99,1.17,195.06,1.07
max,2019.0,20566034.00,1433.78,798.81,4.35,1.015442e+08,0.81,1.25,219595.21,110343.11,...,11.61,13.63,-0.29,1.69,1.77,1.89,1.16,1.56,221.20,1.21

## GDP per worker

In [29]:
var_log_y_pw = np.var(pwt_subset['log_y_pw'])
round(var_log_y_pw,2)

1.13

In [30]:
var_log_y_pc = np.var(pwt_subset['log_y_pc'])
round(var_log_y_pc,2)

1.37

In [31]:
pwt_subset['log_y_hk_pw']  = np.log(pwt_subset['y_hk_pw'])
var_log_y_hk_pw            = np.var(pwt_subset['log_y_hk_pw'])
round(var_log_y_hk_pw,2)

0.32

In [34]:
var_log_tfp                = np.var(np.log(pwt_subset['ctfp']))
round(var_log_tfp,2)

0.2

In [35]:
success_factors = var_log_y_hk_pw/var_log_y_pw
round(success_factors,2)

0.28

In [36]:
success_TFP = var_log_tfp/var_log_y_pw
round(success_TFP,2)

0.18

In [38]:
round((success_factors + success_TFP),2)

0.46

**Conclusion 1:**

* Factors of production alone can explain 28% of the variation in income per worker
* TFP alone can explain 18% of the variation in income per worker
* More than half of the variation in income per worker remains unexplained
* A full variance decomposition needs to be performed to find out the determinants of the unexplained fraction of the variance

In [ ]:
#Outliers

In [47]:
ypw_p99_p01_ratio    = pwt_subset['log_y_pw'].quantile(0.99)/pwt_subset['log_y_pw'].quantile(0.01)
yhk_pw_p99_p01_ratio = pwt_subset['log_y_hk_pw'].quantile(0.99)/pwt_subset['log_y_hk_pw'].quantile(0.01)
ypw_p99_p01_ratio,yhk_pw_p99_p01_ratio

(1.5785783563904698, 1.6482788532646468)

In [48]:
ypw_p95_p05_ratio    = pwt_subset['log_y_pw'].quantile(0.95)/pwt_subset['log_y_pw'].quantile(0.05)
yhk_pw_p95_p05_ratio = pwt_subset['log_y_hk_pw'].quantile(0.95)/pwt_subset['log_y_hk_pw'].quantile(0.05)
ypw_p95_p05_ratio,yhk_pw_p95_p05_ratio

(1.3623812529149488, 1.4893158744877246)

In [49]:
ypw_p90_p10_ratio    = pwt_subset['log_y_pw'].quantile(0.90)/pwt_subset['log_y_pw'].quantile(0.10)
yhk_pw_p90_p10_ratio = pwt_subset['log_y_hk_pw'].quantile(0.90)/pwt_subset['log_y_hk_pw'].quantile(0.10)
ypw_p90_p10_ratio,yhk_pw_p90_p10_ratio

(1.2750406150376261, 1.3929862550861756)

In [50]:
ypw_p75_p25_ratio    = pwt_subset['log_y_pw'].quantile(0.75)/pwt_subset['log_y_pw'].quantile(0.25)
yhk_pw_p75_p25_ratio = pwt_subset['log_y_hk_pw'].quantile(0.75)/pwt_subset['log_y_hk_pw'].quantile(0.25)
ypw_p75_p25_ratio,yhk_pw_p75_p25_ratio

(1.141663455282665, 1.177041633081877)

In [51]:
success1_pw_99_01 = yhk_pw_p99_p01_ratio/ypw_p99_p01_ratio
success1_pw_99_01

1.0441539671388578

In [52]:
success1_pw_95_05 = yhk_pw_p95_p05_ratio/ypw_p95_p05_ratio
success1_pw_95_05

1.0931711452291248

In [53]:
success1_pw_90_10 = yhk_pw_p90_p10_ratio/ypw_p90_p10_ratio
success1_pw_90_10

1.092503437661136

In [54]:
success1_pw_75_25 = yhk_pw_p75_p25_ratio/ypw_p75_p25_ratio
success1_pw_75_25

1.030988272100251

**Conclusion 2:**

* It seems that under the second measure proposed by Caselli, factors of production explain more than 100% of the variation in income per worker
* *This seems odd. If I didn't make any mistakes, it seems that outliers are big drivers of the results obtained in Conclusion 1.*
* Bottomline: if there is no mistake, we really need to think about outliers. An idea is to perform a variance decomposition but using samples without outliers and different regions of the world, and also samples over certain thresholds (i.e. over the median, over the25th percentilem etc)

## Disecting the Measure of Success

###  1. Shuting Down the Variation in Labour Shares

We start by recalculating the measures of success but shitting down the variation in labour shares. We do two alternative calculations:

 * **Alternative 1**: Fix the labour share at 2/3, the most widely used value for in the literature
 * **Alternative 2**: Fix the labour share at the median of the pwt sample in 2019: 0.56

In [ ]:
pwt_subset['y_hk_pw_alt1'] = (pwt_subset['cn']**(1/3))*((pwt_subset['emp']*pwt_subset['avh']*pwt_subset['hc'])**(2/3))
pwt_subset['y_hk_pw_alt1'] = pwt_subset['y_hk_pw_alt1']/pwt_subset['emp']

In [ ]:
log_var_y_hk_pw_alt1 = np.log(np.var(pwt_subset['y_hk_pw_alt1']))
log_var_y_hk_pw_alt1

In [ ]:
success1_pw_alt1 = log_var_y_hk_pw_alt1/log_var_y_pw

In [ ]:
print("The Measure of Success Under *Alternative 1* is:") 
success1_pw_alt1.round(2)

In [ ]:
0.82/0.95

In [ ]:
pwt_subset['y_hk_pw_alt2'] = (pwt_subset['cn']**(1-0.56))*((pwt_subset['emp']*pwt_subset['avh']*pwt_subset['hc'])**(0.56))
pwt_subset['y_hk_pw_alt2'] = pwt_subset['y_hk_pw_alt2']/pwt_subset['emp']

In [ ]:
log_var_y_hk_pw_alt2 = np.log(np.var(pwt_subset['y_hk_pw_alt2']))
log_var_y_hk_pw_alt2.round(2)

In [ ]:
success1_pw_alt2 = log_var_y_hk_pw_alt2/log_var_y_pw

In [ ]:
print("The Measure of Success Under *Alternative 2* is:") 
success1_pw_alt2.round(2)

We choose **Alternative 1** to err on the conservative side. Shutting down the variability coming from differentials in factor intensities, we find that factors of production explain 81% of the variance in output per worker across countries.

### Variance Decomposition

To perform a full variance decomposition we need to calculate a few moments first.

In [ ]:
var_log_y_hk     = np.var(np.log(pwt_subset['y_hk_pw_alt1']))
var_log_y_hk

In [ ]:
var_log_k     = np.var(np.log(pwt_subset['k']))

In [ ]:
var_log_avh   = np.var(np.log(pwt_subset['avh']))

In [ ]:
var_log_h     = np.var(np.log(pwt_subset['hc']))

In [ ]:
cov_log_avh_h = np.cov(np.log(pwt_subset['avh']),np.log(pwt_subset['hc']))[0][1]

In [ ]:
cov_log_k_h   = np.cov(np.log(pwt_subset['k']),np.log(pwt_subset['hc']))[0][1]

In [ ]:
cov_log_k_avh = np.cov(np.log(pwt_subset['k']),np.log(pwt_subset['avh']))[0][1]

In [ ]:
α             = 1/3

In [ ]:
((α**2)*var_log_k)/var_log_y_hk

In [ ]:
(((1-α)**2)*var_log_avh)/var_log_y_hk

In [ ]:
(((1-α)**2)*var_log_h)/var_log_y_hk

In [ ]:
(2*((1-α)**2)*cov_log_avh_h)/var_log_y_hk

In [ ]:
(2*α*(1-α)*cov_log_k_h)/var_log_y_hk

In [ ]:
(2*α*(1-α)*cov_log_k_avh)/var_log_y_hk

In [ ]:
total_variation = np.abs(((α**2)*var_log_k)) + np.abs((((1-α)**2)*var_log_avh)) + np.abs((((1-α)**2)*var_log_h)) + np.abs((2*((1-α)**2)*cov_log_avh_h)) + np.abs((2*α*(1-α)*cov_log_k_h)) + np.abs((2*α*(1-α)*cov_log_k_avh))

In [ ]:
total_variation.round(2)

In [ ]:
#The share of the total variation given by capital per worker is

In [ ]:
(np.abs(((α**2)*var_log_k))/total_variation).round(2)

In [ ]:
#The share of the total variation given by hours worked is
(np.abs((((1-α)**2)*var_log_avh))/total_variation).round(2)

In [ ]:
#The share of the total variation given by hours worked is
(np.abs((((1-α)**2)*var_log_h))/total_variation).round(2)

In [ ]:
#The share of the total variation given by the interaction between hours worked and human capital
(np.abs((2*((1-α)**2)*cov_log_avh_h))/total_variation).round(2)

In [ ]:
#The share of the total variation given by the interaction between capital and human capital
(np.abs((2*α*(1-α)*cov_log_k_h))/total_variation).round(2)

In [ ]:
#The share of the total variation given by the interaction between capital and hours worked is
(np.abs((2*α*(1-α)*cov_log_k_avh))/total_variation).round(2)

## Conclusion

We perform a development accounting exercise ala Caselli, using PWT 10.0. We find that:

 * Factors of production explain 95% of the variation in income per worker
       * Out of that total variation, 86% is driven by pure factors of production, like capital, human capital, and hours worked, while the remaining 14% is explained by differences in factor shares across countries.
       * Within factors of production, differences in capital per worker explain 42% of the total variation, while human capital and hours account for 7% each.
       * We find that richer countries tend to have both higher levels of physical and human capital, with the joint comovement between these two factors of production explaining 21% of the share of income explained by factors only.
       * Moreover, rich countries tend to have higher levels of physical capital and lower levels of hours worked per worker, which reduces the total varition driven by factors of production, helping to explain 17% of the variation that is purely driven by productive factors
       * A remaining 5% of the total income differences explained by production factors is driven by the fact that in countries with higher levels of human capital workers tend to work fewer hours.

In [ ]:
#Suppose that we require our benchmark sample to have data on cgdpo, pop, cn, emp, and hc
#Now we want to see what the bias is due to sample selection in the following cases:
#1. Is the sample of countries that have data on cgdpo, pop, cn, emp, and hc (sample 1) different from the sample that has data on cgdpo, pop, cn, emp only (sample 2)?
#2. Is the sample of countries that have data on cgdpo, pop, cn, emp, hc, and labsh (sample 3) different from samples 1 and 2?
#3. Is the sample of countries that have data on cgdpo, pop, cn, emp, hc, labsh, and ctfp (sample 4) different from samples 1, 2, and 3?
#4. Is the sample of countries that have data on cgdpo, pop, cn, emp, hc, labsh, ctfp, and avh (sample 5) different from samples 1, 2, 3, and 4?

#Here we want to have descriptive statistics  for each sample on gdp per worker and per capita, capital per worker, and employment per capita
#We also want to do charts
#Then we compute the measures of success for each country